/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as ApiPublicAvCatalogRouteImport } from './routes/api/public/av-catalog'
import { Route as ApiPublicAvCreateOrderRouteImport } from './routes/api/public/av-create-order'
import { Route as ApiPublicAvOrderViewRouteImport } from './routes/api/public/av-order-view'
import { Route as ApiPublicAvPaymentInfoRouteImport } from './routes/api/public/av-payment-info'
import { Route as ApiPublicAvPaymentReceiptRouteImport } from './routes/api/public/av-payment-receipt'
import { Route as ApiAdminAuthLoginRouteImport } from './routes/api/admin/auth/login'
import { Route as ApiAdminAuthLogoutRouteImport } from './routes/api/admin/auth/logout'
import { Route as ApiAdminAuthMeRouteImport } from './routes/api/admin/auth/me'
import { Route as ApiAdminAuthRecoveryRouteImport } from './routes/api/admin/auth/recovery'
import { Route as ApiAdminAuthRecoveryCallbackRouteImport } from './routes/api/admin/auth/recovery-callback'
import { Route as ApiAdminAuthResetPasswordRouteImport } from './routes/api/admin/auth/reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicAvCatalogRoute = ApiPublicAvCatalogRouteImport.update({
  id: '/api/public/av-catalog',
  path: '/api/public/av-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvCreateOrderRoute = ApiPublicAvCreateOrderRouteImport.update({
  id: '/api/public/av-create-order',
  path: '/api/public/av-create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvOrderViewRoute = ApiPublicAvOrderViewRouteImport.update({
  id: '/api/public/av-order-view',
  path: '/api/public/av-order-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvPaymentInfoRoute = ApiPublicAvPaymentInfoRouteImport.update({
  id: '/api/public/av-payment-info',
  path: '/api/public/av-payment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvPaymentReceiptRoute =
  ApiPublicAvPaymentReceiptRouteImport.update({
    id: '/api/public/av-payment-receipt',
    path: '/api/public/av-payment-receipt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAuthLoginRoute = ApiAdminAuthLoginRouteImport.update({
  id: '/api/admin/auth/login',
  path: '/api/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLogoutRoute = ApiAdminAuthLogoutRouteImport.update({
  id: '/api/admin/auth/logout',
  path: '/api/admin/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthMeRoute = ApiAdminAuthMeRouteImport.update({
  id: '/api/admin/auth/me',
  path: '/api/admin/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRecoveryRoute = ApiAdminAuthRecoveryRouteImport.update({
  id: '/api/admin/auth/recovery',
  path: '/api/admin/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRecoveryCallbackRoute =
  ApiAdminAuthRecoveryCallbackRouteImport.update({
    id: '/api/admin/auth/recovery-callback',
    path: '/api/admin/auth/recovery-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAuthResetPasswordRoute =
  ApiAdminAuthResetPasswordRouteImport.update({
    id: '/api/admin/auth/reset-password',
    path: '/api/admin/auth/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/av-catalog': typeof ApiPublicAvCatalogRoute
  '/api/public/av-create-order': typeof ApiPublicAvCreateOrderRoute
  '/api/public/av-order-view': typeof ApiPublicAvOrderViewRoute
  '/api/public/av-payment-info': typeof ApiPublicAvPaymentInfoRoute
  '/api/public/av-payment-receipt': typeof ApiPublicAvPaymentReceiptRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/auth/recovery': typeof ApiAdminAuthRecoveryRoute
  '/api/admin/auth/recovery-callback': typeof ApiAdminAuthRecoveryCallbackRoute
  '/api/admin/auth/reset-password': typeof ApiAdminAuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/av-catalog': typeof ApiPublicAvCatalogRoute
  '/api/public/av-create-order': typeof ApiPublicAvCreateOrderRoute
  '/api/public/av-order-view': typeof ApiPublicAvOrderViewRoute
  '/api/public/av-payment-info': typeof ApiPublicAvPaymentInfoRoute
  '/api/public/av-payment-receipt': typeof ApiPublicAvPaymentReceiptRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/auth/recovery': typeof ApiAdminAuthRecoveryRoute
  '/api/admin/auth/recovery-callback': typeof ApiAdminAuthRecoveryCallbackRoute
  '/api/admin/auth/reset-password': typeof ApiAdminAuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/av-catalog': typeof ApiPublicAvCatalogRoute
  '/api/public/av-create-order': typeof ApiPublicAvCreateOrderRoute
  '/api/public/av-order-view': typeof ApiPublicAvOrderViewRoute
  '/api/public/av-payment-info': typeof ApiPublicAvPaymentInfoRoute
  '/api/public/av-payment-receipt': typeof ApiPublicAvPaymentReceiptRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/auth/recovery': typeof ApiAdminAuthRecoveryRoute
  '/api/admin/auth/recovery-callback': typeof ApiAdminAuthRecoveryCallbackRoute
  '/api/admin/auth/reset-password': typeof ApiAdminAuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/'
    | '/api/public/av-catalog'
    | '/api/public/av-create-order'
    | '/api/public/av-order-view'
    | '/api/public/av-payment-info'
    | '/api/public/av-payment-receipt'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/auth/recovery'
    | '/api/admin/auth/recovery-callback'
    | '/api/admin/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin'
    | '/api/public/av-catalog'
    | '/api/public/av-create-order'
    | '/api/public/av-order-view'
    | '/api/public/av-payment-info'
    | '/api/public/av-payment-receipt'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/auth/recovery'
    | '/api/admin/auth/recovery-callback'
    | '/api/admin/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/'
    | '/api/public/av-catalog'
    | '/api/public/av-create-order'
    | '/api/public/av-order-view'
    | '/api/public/av-payment-info'
    | '/api/public/av-payment-receipt'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/auth/recovery'
    | '/api/admin/auth/recovery-callback'
    | '/api/admin/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiPublicAvCatalogRoute: typeof ApiPublicAvCatalogRoute
  ApiPublicAvCreateOrderRoute: typeof ApiPublicAvCreateOrderRoute
  ApiPublicAvOrderViewRoute: typeof ApiPublicAvOrderViewRoute
  ApiPublicAvPaymentInfoRoute: typeof ApiPublicAvPaymentInfoRoute
  ApiPublicAvPaymentReceiptRoute: typeof ApiPublicAvPaymentReceiptRoute
  ApiAdminAuthLoginRoute: typeof ApiAdminAuthLoginRoute
  ApiAdminAuthLogoutRoute: typeof ApiAdminAuthLogoutRoute
  ApiAdminAuthMeRoute: typeof ApiAdminAuthMeRoute
  ApiAdminAuthRecoveryRoute: typeof ApiAdminAuthRecoveryRoute
  ApiAdminAuthRecoveryCallbackRoute: typeof ApiAdminAuthRecoveryCallbackRoute
  ApiAdminAuthResetPasswordRoute: typeof ApiAdminAuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/av-catalog': {
      id: '/api/public/av-catalog'
      path: '/api/public/av-catalog'
      fullPath: '/api/public/av-catalog'
      preLoaderRoute: typeof ApiPublicAvCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-create-order': {
      id: '/api/public/av-create-order'
      path: '/api/public/av-create-order'
      fullPath: '/api/public/av-create-order'
      preLoaderRoute: typeof ApiPublicAvCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-order-view': {
      id: '/api/public/av-order-view'
      path: '/api/public/av-order-view'
      fullPath: '/api/public/av-order-view'
      preLoaderRoute: typeof ApiPublicAvOrderViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-payment-info': {
      id: '/api/public/av-payment-info'
      path: '/api/public/av-payment-info'
      fullPath: '/api/public/av-payment-info'
      preLoaderRoute: typeof ApiPublicAvPaymentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-payment-receipt': {
      id: '/api/public/av-payment-receipt'
      path: '/api/public/av-payment-receipt'
      fullPath: '/api/public/av-payment-receipt'
      preLoaderRoute: typeof ApiPublicAvPaymentReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/login': {
      id: '/api/admin/auth/login'
      path: '/api/admin/auth/login'
      fullPath: '/api/admin/auth/login'
      preLoaderRoute: typeof ApiAdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/logout': {
      id: '/api/admin/auth/logout'
      path: '/api/admin/auth/logout'
      fullPath: '/api/admin/auth/logout'
      preLoaderRoute: typeof ApiAdminAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/me': {
      id: '/api/admin/auth/me'
      path: '/api/admin/auth/me'
      fullPath: '/api/admin/auth/me'
      preLoaderRoute: typeof ApiAdminAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/recovery': {
      id: '/api/admin/auth/recovery'
      path: '/api/admin/auth/recovery'
      fullPath: '/api/admin/auth/recovery'
      preLoaderRoute: typeof ApiAdminAuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/recovery-callback': {
      id: '/api/admin/auth/recovery-callback'
      path: '/api/admin/auth/recovery-callback'
      fullPath: '/api/admin/auth/recovery-callback'
      preLoaderRoute: typeof ApiAdminAuthRecoveryCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/reset-password': {
      id: '/api/admin/auth/reset-password'
      path: '/api/admin/auth/reset-password'
      fullPath: '/api/admin/auth/reset-password'
      preLoaderRoute: typeof ApiAdminAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiPublicAvCatalogRoute: ApiPublicAvCatalogRoute,
  ApiPublicAvCreateOrderRoute: ApiPublicAvCreateOrderRoute,
  ApiPublicAvOrderViewRoute: ApiPublicAvOrderViewRoute,
  ApiPublicAvPaymentInfoRoute: ApiPublicAvPaymentInfoRoute,
  ApiPublicAvPaymentReceiptRoute: ApiPublicAvPaymentReceiptRoute,
  ApiAdminAuthLoginRoute: ApiAdminAuthLoginRoute,
  ApiAdminAuthLogoutRoute: ApiAdminAuthLogoutRoute,
  ApiAdminAuthMeRoute: ApiAdminAuthMeRoute,
  ApiAdminAuthRecoveryRoute: ApiAdminAuthRecoveryRoute,
  ApiAdminAuthRecoveryCallbackRoute: ApiAdminAuthRecoveryCallbackRoute,
  ApiAdminAuthResetPasswordRoute: ApiAdminAuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
