/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAvCatalogRouteImport } from './routes/api/public/av-catalog'
import { Route as ApiPublicAvCreateOrderRouteImport } from './routes/api/public/av-create-order'
import { Route as ApiPublicAvOrderViewRouteImport } from './routes/api/public/av-order-view'
import { Route as ApiPublicAvPaymentInfoRouteImport } from './routes/api/public/av-payment-info'
import { Route as ApiPublicAvPaymentReceiptRouteImport } from './routes/api/public/av-payment-receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvCatalogRoute = ApiPublicAvCatalogRouteImport.update({
  id: '/api/public/av-catalog',
  path: '/api/public/av-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvCreateOrderRoute = ApiPublicAvCreateOrderRouteImport.update({
  id: '/api/public/av-create-order',
  path: '/api/public/av-create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvOrderViewRoute = ApiPublicAvOrderViewRouteImport.update({
  id: '/api/public/av-order-view',
  path: '/api/public/av-order-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvPaymentInfoRoute = ApiPublicAvPaymentInfoRouteImport.update({
  id: '/api/public/av-payment-info',
  path: '/api/public/av-payment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvPaymentReceiptRoute =
  ApiPublicAvPaymentReceiptRouteImport.update({
    id: '/api/public/av-payment-receipt',
    path: '/api/public/av-payment-receipt',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/av-catalog': typeof ApiPublicAvCatalogRoute
  '/api/public/av-create-order': typeof ApiPublicAvCreateOrderRoute
  '/api/public/av-order-view': typeof ApiPublicAvOrderViewRoute
  '/api/public/av-payment-info': typeof ApiPublicAvPaymentInfoRoute
  '/api/public/av-payment-receipt': typeof ApiPublicAvPaymentReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/av-catalog': typeof ApiPublicAvCatalogRoute
  '/api/public/av-create-order': typeof ApiPublicAvCreateOrderRoute
  '/api/public/av-order-view': typeof ApiPublicAvOrderViewRoute
  '/api/public/av-payment-info': typeof ApiPublicAvPaymentInfoRoute
  '/api/public/av-payment-receipt': typeof ApiPublicAvPaymentReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/av-catalog': typeof ApiPublicAvCatalogRoute
  '/api/public/av-create-order': typeof ApiPublicAvCreateOrderRoute
  '/api/public/av-order-view': typeof ApiPublicAvOrderViewRoute
  '/api/public/av-payment-info': typeof ApiPublicAvPaymentInfoRoute
  '/api/public/av-payment-receipt': typeof ApiPublicAvPaymentReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/av-catalog'
    | '/api/public/av-create-order'
    | '/api/public/av-order-view'
    | '/api/public/av-payment-info'
    | '/api/public/av-payment-receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/av-catalog'
    | '/api/public/av-create-order'
    | '/api/public/av-order-view'
    | '/api/public/av-payment-info'
    | '/api/public/av-payment-receipt'
  id:
    | '__root__'
    | '/'
    | '/api/public/av-catalog'
    | '/api/public/av-create-order'
    | '/api/public/av-order-view'
    | '/api/public/av-payment-info'
    | '/api/public/av-payment-receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAvCatalogRoute: typeof ApiPublicAvCatalogRoute
  ApiPublicAvCreateOrderRoute: typeof ApiPublicAvCreateOrderRoute
  ApiPublicAvOrderViewRoute: typeof ApiPublicAvOrderViewRoute
  ApiPublicAvPaymentInfoRoute: typeof ApiPublicAvPaymentInfoRoute
  ApiPublicAvPaymentReceiptRoute: typeof ApiPublicAvPaymentReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-catalog': {
      id: '/api/public/av-catalog'
      path: '/api/public/av-catalog'
      fullPath: '/api/public/av-catalog'
      preLoaderRoute: typeof ApiPublicAvCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-create-order': {
      id: '/api/public/av-create-order'
      path: '/api/public/av-create-order'
      fullPath: '/api/public/av-create-order'
      preLoaderRoute: typeof ApiPublicAvCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-order-view': {
      id: '/api/public/av-order-view'
      path: '/api/public/av-order-view'
      fullPath: '/api/public/av-order-view'
      preLoaderRoute: typeof ApiPublicAvOrderViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-payment-info': {
      id: '/api/public/av-payment-info'
      path: '/api/public/av-payment-info'
      fullPath: '/api/public/av-payment-info'
      preLoaderRoute: typeof ApiPublicAvPaymentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/av-payment-receipt': {
      id: '/api/public/av-payment-receipt'
      path: '/api/public/av-payment-receipt'
      fullPath: '/api/public/av-payment-receipt'
      preLoaderRoute: typeof ApiPublicAvPaymentReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAvCatalogRoute: ApiPublicAvCatalogRoute,
  ApiPublicAvCreateOrderRoute: ApiPublicAvCreateOrderRoute,
  ApiPublicAvOrderViewRoute: ApiPublicAvOrderViewRoute,
  ApiPublicAvPaymentInfoRoute: ApiPublicAvPaymentInfoRoute,
  ApiPublicAvPaymentReceiptRoute: ApiPublicAvPaymentReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
